package controller;

public enum Commands {

	C_SHOW_NEW_INCOME,C_NEW_PROD, C_CREATE_PEOPLE, C_CANCEL_CREATE_INCOME, DELETE,FIND,
	C_NEW_ELEMENT, C_ES_LANGUAGE, C_US_LANGUAGE, C_AVERAGE, C_MENU_ABOUT, C_EXIT,
	C_ADDPRODUCT,
	C_SHOW_NEW_COST, C_LOGIN, C_INGRES;
	
	

}
